import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { SYSTEM_PROMPT } from "./voice/agentConfig.js";

/**
 * `agent-prompt.md` is a paste-able copy of the system prompt, regenerated by
 * `pnpm sync-agent`. It once drifted to less than half the real prompt, which meant
 * anyone configuring the agent by hand in the dashboard got an agent missing most of
 * its rules — with nothing in the code to show why it misbehaved.
 */
describe("agent-prompt.md", () => {
  it("still matches SYSTEM_PROMPT", () => {
    const md = readFileSync(new URL("../agent-prompt.md", import.meta.url), "utf8");
    const body = md.replace(/^<!--[\s\S]*?-->\s*/, "").trim();
    expect(body, "run `pnpm sync-agent` to regenerate agent-prompt.md").toBe(SYSTEM_PROMPT.trim());
  });
});
